Backend initialisation
profcomff/services-api pull request #1
Opened 2022-12-05 17:42 UTC by Wudext

2022-12-05 18:09 UTC, grigoriev-semyon requested changes

2022-12-05 18:09 UTC, grigoriev-semyon commented on .gitignore
> +.idea
в Глобал

2022-12-05 18:09 UTC, grigoriev-semyon commented on .gitignore
> +desktop.ini
убрать тоже куда нибудь в глобал

2022-12-05 18:09 UTC, grigoriev-semyon commented on migrations/versions/6739a3c84646_update_1_0.py
> +"""Update 1.0
убери комменты отсюда лучше

2022-12-05 18:09 UTC, grigoriev-semyon commented on requirements.dev.txt
> +Faker
тоже не нужен уже

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/models/database.py
> +    category = relationship("Category", back_populates="button")
думаю упадет при первом использовании 
надо добавить foriegn_keys=[category_id]

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/models/database.py
> +    button = relationship("Button", back_populates="category")
а сюда
foreign_keys="Button.category_id"

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +    if db_category is None:
if not db_category:
...

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +                             icon=button.icon)
db_button = Button(**button.dict())

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +def get_buttons(skip: int = 0, limit: int = 100):
skip переименуй в offset лучше

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +def remove_button(button_id: int):
response_model=None

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +
пустая строка

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +    if db_category is None:
везде в остальных местах лучше так же

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +    db_old_button = db.session.query(Button).filter(Button.id == button_id).one_or_none()
button переименуй лучше в button_inp
db_old_button на button

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +    db_category = Category(type=category.type, name=category.name)
db_category = Category(**category.dict())

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +    db_category = Category(type=category.type, name=category.name)
еще лучше тоже переименовать category на category_inp
db_category на category

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +def get_categories(skip: int = 0, limit: int = 100):
skip на offset поменяй тут тоже а то непонятно

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +    db_category = db.session.query(Category).filter(Category.id == category_id).one_or_none()
просто category

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +    for button in d:
for button in db.session.query(Button).filter(Button.category_id == category_id).all():

Зачем создавать переменную?

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +    return db_old_category
тоже пустые строки

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +    db_old_category = db.session.query(Category).filter(Category.id == category_id).one_or_none()
тоже лучше category_inp и category

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/models/button.py
> +    icon: Optional[str]
str | None

2022-12-05 18:09 UTC, grigoriev-semyon commented on services_backend/routes/models/category.py
> +    type: Optional[str]
тут тоже

2022-12-06 21:13 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +@button.delete("/")
button_id в path параметры

2022-12-07 18:03 UTC, Wudext commented on services_backend/models/database.py
> +    category = relationship("Category", back_populates="button")
Нет, не сработало, на stack все говорят использовать ForeignKey (как у меня), ключа foreign_keys вообще походу нет.

2022-12-07 18:08 UTC, Wudext commented on services_backend/models/database.py
> +    button = relationship("Button", back_populates="category")
Не получится использовать до инициализации класса Button. Если сначала инициализировать Button, ломается ForeignKey в Button (так как Category еще не инициализирован).

2022-12-07 18:10 UTC, Wudext commented on services_backend/routes/button.py
> +                             icon=button.icon)
Unexpected argument

2022-12-07 18:15 UTC, Wudext commented on services_backend/routes/category.py
> +    db_category = Category(type=category.type, name=category.name)
Unexpected argument

2022-12-07 19:14 UTC, grigoriev-semyon requested changes

2022-12-07 19:14 UTC, grigoriev-semyon commented on migrations/versions/6739a3c84646_update_1_0.py
> +def upgrade():
Дроп в апгрейде? что то тут напутано

2022-12-07 19:14 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +    button = get_button(button_id=button_id)
ручка переиспользуется

2022-12-07 19:14 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +    category = get_category(category_id=category_id)
ручка переиспользуется

2022-12-07 19:23 UTC, grigoriev-semyon approved these changes

2022-12-07 19:26 UTC, merged