Adding #10
profcomff/services-api pull request #11
Opened 2023-02-02 16:11 UTC by Wudext

2023-02-02 16:15 UTC, dyakovri commented on migrations/versions/670f4caac7dd_init.py
> -    op.drop_table('category')
Верни))

2023-02-02 16:17 UTC, dyakovri commented on services_backend/models/database.py
> +>>>>>>> Stashed changes
Это что за последствия незавершенного мержа веток?

2023-02-02 16:18 UTC, dyakovri commented on services_backend/routes/models/button.py
Почему это Dict, а не Link, например?

2023-02-02 16:18 UTC, dyakovri commented on services_backend/routes/models/button.py
> +>>>>>>> Stashed changes
Опять незавершенный мерж

2023-02-02 16:20 UTC, Wudext commented on services_backend/routes/models/button.py
Dict это тип данных, а название link

2023-02-02 16:20 UTC, Wudext commented on services_backend/routes/models/button.py
> +>>>>>>> Stashed changes
Было такое...

2023-02-02 16:21 UTC, Wudext commented on services_backend/routes/models/button.py
> +>>>>>>> Stashed changes
Но я же вроде в последнем коммите убрал это все

2023-02-02 18:11 UTC, grigoriev-semyon commented on services_backend/routes/models/button.py
> +>>>>>>> Stashed changes
тесты из за этого падают

2023-02-03 20:10 UTC, mixx3 approved these changes, later dismissed
красивое

2023-02-03 20:20 UTC, grigoriev-semyon requested changes

2023-02-03 20:20 UTC, grigoriev-semyon commented on .gitignore
> +.idea/workspace.xml
в Глобал

2023-02-03 20:20 UTC, grigoriev-semyon commented on migrations/versions/670f4caac7dd_init.py
> +    sa.Column('link', sa.String(), nullable=True),
зачем поменялась

2023-02-03 20:20 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +    return button.one()
сессия уже сдохла это надо раньше коммита  делать

2023-02-03 20:20 UTC, grigoriev-semyon commented on services_backend/routes/button.py
>      db.session.flush()
флаш убери, коммит делает флаш автоматом

2023-02-03 20:20 UTC, grigoriev-semyon commented on services_backend/routes/category.py
>      db.session.flush()
тут тоже флаш

2023-02-03 20:20 UTC, grigoriev-semyon commented on services_backend/routes/category.py
>      db.session.flush()
и тут

2023-02-03 20:20 UTC, grigoriev-semyon commented on tests/api/conftest.py
> +        dbsession.flush()
флаш!

2023-02-03 20:21 UTC, grigoriev-semyon commented
+6 тестов на логику ордеринга

2023-02-11 07:20 UTC, grigoriev-semyon commented on services_backend/routes/category.py
> +    return category.one()
сессия сдохла уже
После коммита сессия закрывается она НЕ делает запросы больше

2023-02-11 07:23 UTC, Wudext commented on services_backend/routes/category.py
> +    return category.one()
Мы возвращаем не объект, относящийся к сессии, а локальный объект. Если commit поставить после return, функция выйдет раньше commit и не будет изменений в бд.

2023-02-13 08:08 UTC, grigoriev-semyon requested changes
обсуждали все в Дисе

2023-02-13 16:52 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +        "type": button.type}
просто button

2023-02-13 17:00 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +            .filter(Button.order > button.one().order) \
несколько одинаковых запросов

2023-02-13 17:00 UTC, grigoriev-semyon commented on services_backend/routes/button.py
>      if not any(button_inp.dict().values()):
че за any

2023-02-13 17:08 UTC, grigoriev-semyon commented on services_backend/routes/category.py
>      db.session.delete(delete)
delete - плохое название для файла

2023-02-13 17:08 UTC, grigoriev-semyon commented on services_backend/routes/category.py
>      )
опять несколько однотипных запросов к БД

2023-02-13 17:11 UTC, grigoriev-semyon requested changes
уже почти можно мерджить...

2023-02-14 14:27 UTC, Wudext commented on services_backend/routes/button.py
>      if not any(button_inp.dict().values()):
Так надо

2023-02-14 16:20 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +@button.get("/", response_model=CategoryGet, response_model_exclude_unset=True)
а зачем тут response_model_exclude_unset?

2023-02-14 16:25 UTC, Wudext commented on services_backend/routes/button.py
> +@button.get("/", response_model=CategoryGet, response_model_exclude_unset=True)
хз)

2023-02-14 17:23 UTC, grigoriev-semyon approved these changes

2023-02-14 17:24 UTC, merged