Issues #22, #28, #29, README.md update
profcomff/services-api pull request #30
Opened 2023-03-30 15:14 UTC by Wudext

2023-03-31 13:23 UTC, grigoriev-semyon requested changes
Я не вижу здесь изменений которые фиксят #28, #29
Вижу костыль на один ишью из трех
Пайдентик должен справляться с таким сам

2023-03-31 13:23 UTC, grigoriev-semyon commented on .gitignore
> +*.iml
Глобал гитигнор

2023-03-31 13:23 UTC, grigoriev-semyon commented on CONTRIBUTING.md
> +Локальную БД можно поднять так: ссылка на вики которой нет
ну две команды можно и тут написать)

2023-03-31 13:23 UTC, grigoriev-semyon commented on CONTRIBUTING.md
> +1) DB_DSN = 'postgres://логин:пароль/@адресс:порт/бд'
можно такие вещи на англе пж

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +Бэкэдн сервисов приложения Твой ФФ для профкома ФФ МГУ. Описывает и реализует логику работы с кнопками и категориями в приложении.
бэкедн

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +Бэкэдн сервисов приложения Твой ФФ для профкома ФФ МГУ. Описывает и реализует логику работы с кнопками и категориями в приложении.
как это он описывает? описывает дока

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +Репозиторий был создан для упрощения работы фронтэнд-разработчиков с бэкэндом сервисов и для переноса данных кнопок и категорий из захардкодженного json файла в Postgresql базу данных (cringe).
Вообще, в первую очередь, задумывался сервис именно для разграничения доступов

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +CONTRIBUTING.md - нету
есть

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +- Управление доступами к категориями кнопок
категориям

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +- Редактирование любой информации о кнопке и категории
любых атрибутов/полей

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +4) Установите все переменные окружения (см. CONTRIBUTING.MD)
.md не капсом

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +    2. *Необходимо иметь права services.button.create* Создать в категории новую кнопку по запросу `POST /category/id_категории/button` с телом `{"name": "имя кнопки", "icon": "ссылка на иконку", "li
что такое type? я не понял

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +    3. *Опционально* Навесить права запросом `POST /category/id_категории/scope` с телом `{"name": "название права доступа"}`
/category/{category_id}/scope

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +    2. *Опционально* Выбрать отображение кнопок принадлежащих категории по запросу `GET /category?info=buttons`
Получение категорий кнопок

2023-03-31 13:23 UTC, grigoriev-semyon commented on README.md
> +CONTRIBUTING.md - нету
где то я это уже видел

2023-03-31 13:23 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +            raise HTTPException(status_code=422, detail="Wrong schema")
смахивает на костыль
пайдентик не справился с таким?

2023-03-31 13:23 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +            raise HTTPException(status_code=422, detail="Wrong schema")
да и кидать экепснш после создания Button
смысл?
почему не в обратном порядке?

2023-03-31 13:24 UTC, Wudext commented on README.md
> +    2. *Необходимо иметь права services.button.create* Создать в категории новую кнопку по запросу `POST /category/id_категории/button` с телом `{"name": "имя кнопки", "icon": "ссылка на иконку", "li
Тип отображения в приложении, параметр для фронта

2023-03-31 13:25 UTC, dyakovri commented on CONTRIBUTING.md
> +Локальную БД можно поднять так: ссылка на вики которой нет
Можно самому написать на вики в докуменатцию по бэкэнду

2023-03-31 13:25 UTC, grigoriev-semyon commented on README.md
> +    2. *Необходимо иметь права services.button.create* Создать в категории новую кнопку по запросу `POST /category/id_категории/button` с телом `{"name": "имя кнопки", "icon": "ссылка на иконку", "li
а почему не написать об этом в доке?)

2023-03-31 13:25 UTC, Wudext commented on services_backend/routes/button.py
> +            raise HTTPException(status_code=422, detail="Wrong schema")
Пайдантик к сожалению с таким не справляется, кидает 500

2023-03-31 13:26 UTC, grigoriev-semyon commented on README.md
> +    2. *Необходимо иметь права services.button.create* Создать в категории новую кнопку по запросу `POST /category/id_категории/button` с телом `{"name": "имя кнопки", "icon": "ссылка на иконку", "li
хотя бы в доке которая swagger
а то у тебя нигде нет

2023-03-31 13:26 UTC, dyakovri commented on CONTRIBUTING.md
> +1) DB_DSN = 'postgres://логин:пароль/@адресс:порт/бд'
Да на русском можно, но только без ошибок
Адрес с одной с, после пароля слеш не нужен

2023-03-31 13:27 UTC, dyakovri commented on README.md
> +CONTRIBUTING.md - нету
Но контрибьютинг ты же написал и даже скидывал

2023-03-31 13:30 UTC, Wudext commented on README.md
> +CONTRIBUTING.md - нету
Да, просто надо на него ссылку сделать. До этого его на гите не было, ща добавлю ссылку

2023-04-06 12:02 UTC, grigoriev-semyon requested changes

2023-04-06 12:02 UTC, grigoriev-semyon commented on services_backend/routes/models/category.py
> +    type: str = Field(description='Тип отображения категории')
добавь enum

2023-04-06 12:02 UTC, grigoriev-semyon commented on services_backend/routes/models/category.py
> +    type: str = Field(description='Тип отображения категории')
#32

2023-04-06 12:02 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +            raise HTTPException(status_code=422, detail="Wrong schema")
анрезолвнул

2023-04-06 12:02 UTC, grigoriev-semyon commented on services_backend/routes/button.py
> +            raise HTTPException(status_code=422, detail="Wrong schema")
пайдентик с таким справляется, этот код здесь лишний

2023-04-06 12:02 UTC, grigoriev-semyon commented on README.md
> +    1. Удалить категорию кнопок по запросу 'DELETE /category/id_категории
/category/{category_id}

2023-04-06 12:02 UTC, grigoriev-semyon commented on README.md
> +CONTRIBUTING.md - https://github.com/profcomff/services-api/blob/f22b360ba1ab5ab8e876c26a1cee563c32d36c6b/CONTRIBUTING.md (потом поменяю)
https://stackoverflow.com/questions/11868512/linking-using-relative-path-on-github-readme-md

2023-04-06 12:06 UTC, grigoriev-semyon commented
еще не вижу миграции соответствующей на уход от сквозной нумерации

2023-04-07 17:01 UTC, Wudext commented on services_backend/routes/models/category.py
> +    type: str = Field(description='Тип отображения категории')
TypeError: Object of type 'EnumType' is not JSON serializable

Lmao

2023-04-08 06:45 UTC, grigoriev-semyon requested changes

2023-04-08 06:45 UTC, grigoriev-semyon commented on migrations/versions/6a486347af93_order.py
> +    res_c = conn.execute(sa.text("select * from category")).fetchall()
Это существующая миграция, надо новую

2023-04-08 06:45 UTC, grigoriev-semyon commented on migrations/versions/6a486347af93_order.py
> +        res_b = conn.execute(sa.text(f"select id from button where button.id = {category[0]}")).fetchall()
не отсортировано

2023-04-08 06:45 UTC, grigoriev-semyon commented on migrations/versions/6a486347af93_order.py
> +                                         "type"='external'
всем?

2023-04-08 06:47 UTC, grigoriev-semyon commented on README.md
> +    1. Удалить категорию кнопок по запросу 'DELETE /category/id_категории
анрезовнул

2023-04-08 06:49 UTC, grigoriev-semyon commented on services_backend/routes/models/button.py
> +    type: Type = Field(description='Тип открываемой ссылки')
а почему не обновлены Update и Get?

2023-04-08 06:50 UTC, grigoriev-semyon commented on services_backend/routes/models/button.py
> +    type: Type = Field(description='Тип открываемой ссылки')
что такое type я все равно не понял кстати

2023-04-09 15:27 UTC, grigoriev-semyon requested changes

2023-04-09 15:27 UTC, grigoriev-semyon commented on migrations/versions/d35e88f39f85_fixing.py
> +    pass
Где даунгрейд?)

2023-04-09 15:27 UTC, grigoriev-semyon commented on migrations/versions/d35e88f39f85_fixing.py
> +        res_b = conn.execute(sa.text(f"select * from button WHERE category_id={category[0]}")).fetchall()
Оно не отсортировано

2023-04-10 09:52 UTC, grigoriev-semyon commented on migrations/versions/d35e88f39f85_fixing.py
> +        )
https://www.w3schools.com/sql/sql_orderby.asp

2023-04-10 09:53 UTC, grigoriev-semyon commented on migrations/versions/d35e88f39f85_fixing.py
> +    res_c = conn.execute(sa.text("select * from category")).fetchall()
категории не отсортированы

2023-04-10 11:11 UTC, grigoriev-semyon commented on migrations/versions/6a486347af93_order.py
> -                                     "link"='#',
кавычка

2023-04-10 11:12 UTC, grigoriev-semyon commented on migrations/versions/6a486347af93_order.py
> +                                     "type"='inapp'
зачем эта замена?

2023-04-10 11:12 UTC, grigoriev-semyon commented on migrations/versions/6a486347af93_order.py
> +                                     "link"=#',
а тут нет кавычки

2023-04-10 11:13 UTC, grigoriev-semyon requested changes
уж не знаю как эти миграции запускаются если ты их вообще тестишь

2023-04-10 11:15 UTC, Wudext commented on migrations/versions/6a486347af93_order.py
> +                                     "type"='inapp'
прост))0)

2023-04-10 11:15 UTC, Wudext commented on migrations/versions/6a486347af93_order.py
> -                                     "link"='#',
Тут нужна кавычка или нет?

2023-04-10 11:24 UTC, grigoriev-semyon requested changes

2023-04-10 11:24 UTC, grigoriev-semyon commented on migrations/versions/d35e88f39f85_fixing.py
> +            ).fetchall()
order by и sorted

2023-04-10 11:32 UTC, grigoriev-semyon approved these changes

2023-04-10 11:33 UTC, merged